cargo-features = ["edition2024"]

[package]
name = "ambient-auction-interface"
version = "0.1.0"
edition = "2024"

[dependencies]
pinocchio = "=0.9.2"
ambient-auction-api = { path = "../auction-api" }